# Generated by Django 5.2 on 2025-04-09 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default=None, upload_to='')),
                ('desc', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 4, 9, 9, 45, 18, 65491, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
