# Generated by Django 5.2 on 2025-04-19 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('another', '0005_alter_product_created_at_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 19, 8, 55, 3, 183016, tzinfo=datetime.timezone.utc)),
        ),
    ]
